# Generated by Django 6.0.3 on 2026-04-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Code', max_length=200)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('go', 'Go')], default='python', max_length=20)),
                ('code', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('readability_score', models.FloatField(blank=True, null=True)),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('security_score', models.FloatField(blank=True, null=True)),
                ('best_practices_score', models.FloatField(blank=True, null=True)),
                ('bugs_found', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_data', models.TextField(default='{}')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
